{% set name = "deprecation" %}
{% set version = "2.0.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "e8d0dc5a17d7d551730e5f23ff3a53fc9e438364b9efb47d41c3e9b05522eabe" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - packaging

  run:
    - python
    - packaging

test:
  imports:
    - deprecation

about:
  home: http://deprecation.readthedocs.io/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'A library to handle automated deprecations'
  dev_url: https://github.com/briancurtin/deprecation
  doc_url: http://deprecation.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - kmuehlbauer
