travis:
  secure:
    BINSTAR_TOKEN: qA+yEaJvRfpckgH/pYLx11kb9bGzDq46d2BcsZdc800n87mzNisgf2rwwZF4QXljuVq7fdinoxDevl383gv+gxsFYLyHVGsPVegx9q6bUjQ0Xhky6CEslFA7gVYjFG7c8RCHcIfi2BDnO5g1JotvqlQvptdaHVcAkt46FW31hl0oS0KgHCEHqFxb3vcAzEPFoV9fWzMkYrgPW1gBhloTRoqKAvT7uVNRSPuY5qyekPA4Jnb684i4Wz2iprNDc2//athLsKwicB/IjZJYXfpRAA81NJ/VLUb53MZiQrII9So4IjTEFtSgS3Hjwms/w/5erpnyLWgLqtNBjlVHhviqrK+EDviWVcNDFO+3mnPZsPFiOHzvDduIf6+OuV41DiNSUWii9k+hONTZm80X5oyHPl11L2xA0urZR4O043tm9nDsmzk0GY5ZUVqmmtr6YTe3SfMgvNpBnmkmyTHOnE5LV9ui5sfc9oAA8TMqTVofdCC+hXDx/2j1dMTssGrBS1n2MvI6NBYDaI9HxWsk1OGgFbpZMiHQPeJm9bkGsbkjBtOiYNZ1bemT8gqlNNOAKMmGduZBNfJtdYUeDbkhiittnwUgyG8Ubd3aMfnACvINyd4VJYCG1fm7ZaVOUAbIPJ92Jc+XlJv+rdfaW4YY7hwFCnW7B01MFz2XRUJu9qacpaI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
